on: push

name: Test
jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        buildtype: [Release] #, Debug]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx-10.13
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install
        run: npm install
      - name: make test
        run: make test

  lys-compiler:
    name: lys-compiler build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install
        run: npm install
      - name: make test
        run: make build
      - name: Checkout lys-compiler
        uses: actions/checkout@v4
        with:
          repository: lys-lang/lys-compiler
          path: lys-compiler
      - name: Build and test lys-compiler
        working-directory: ./lys-compiler
        run: |
          make build LYS=../dist/bin.js
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install
        run: npm install
      - name: make lint
        run: make lint

  markdown-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install
        run: npm install
      - name: make e2e
        run: make e2e

  build-publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: ['markdown-test', 'lint', 'test']
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: npm install
        run: npm install
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: 'https://registry.npmjs.org'
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
